# Generated by Django 6.0.3 on 2026-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=35, unique=True)),
                ('Tahun_lahir', models.CharField(max_length=20)),
                ('alamat_lengkap', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=255)),
            ],
        ),
    ]
