# Generated by Django 6.0.3 on 2026-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='Tahun_lahir',
            new_name='tahun_lahir',
        ),
        migrations.AddField(
            model_name='siswa',
            name='nis',
            field=models.CharField(default=0.05, max_length=35, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(default=939393, max_length=35, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama_lengkap',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
