# Generated by Django 6.0.3 on 2026-04-07 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_tahun_lahir_siswa_tahun_lahir_siswa_nis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nama_lengkap',
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_siswa',
            field=models.CharField(default=0.05, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='alamat_lengkap',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kontak',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nik',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tahun_lahir',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='NilaiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.daftarmapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.siswa')),
            ],
            options={
                'unique_together': {('siswa', 'mapel')},
            },
        ),
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.daftarkelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.siswa')),
            ],
            options={
                'unique_together': {('siswa', 'kelas')},
            },
        ),
    ]
